### ISSUE TITLE
Merge por accidente?

### ISSUE THREAD

**Issue by gonzafernan** [FernandezGFG/informatica-2017#12]
Gino no se porque mierda se hace merge algo que quiero hacer push. Volve a subir lo que subiste porfa

**Comment by gonzafernan** [comment]
La puta madre jajajaja no se hace de ahí. Perdón Gino de nuevo jajajajajajajajajaja

**Comment by GinoAvanzini** [comment]
Qué cosa? No sé a qué le hiciste merge jajaja

**Comment by gonzafernan** [comment]
Yo estaba flayando, no me des bola jajajjaa
