### ISSUE TITLE
Idea para casos de error en los ejercicios

### ISSUE THREAD

**Issue by gonzafernan** [FernandezGFG/informatica-2017#17]
Acaba de tirarme el Jero una idea chota, pero que me pareció un detalle copado jajaja cada vez que se ingresa mal algo, como una fecha que no existe, tire un mensaje de error, pregunte si desea continuar (Y/N) y si no cierre el programa. Me pareció copado, por lo menos para practicar y ver si se puede hacer algo más interactivo.

**Comment by GinoAvanzini** [comment]
Y cómo se hace eso? Con un goto?

**Comment by gonzafernan** [comment]
Nose, habría que pensarlo. Es verdad que el go to sería lo más fácil... Pero por ahí hay alguna otra forma de hacerlo.

**Comment by giunta** [comment]
ademas de eso podriamos poner algo asi al final de cada ejercicio para volver al main y abrir otro, supongo que es parecido

**Comment by gonzafernan** [comment]
Claaaaro @giunta algo así se me había ocurrido a mi. De última eso lo podemos agregar cuando tengamos todos los ejercicios hechos

**Comment by ichmew** [comment]
mmm podríamos colocar un condicional al final de cada ejercicio con 2 opciones de return. Entonces con ese valor volvemos al main con una recursión o un goto.
Otra opción sería colocar el condicional al final del main y ahí aplicar el goto o recursión.

**Comment by gonzafernan** [comment]
Recursión después del main me parece una excelente idea che

**Comment by giunta** [comment]
sep con ponerlo en el main se hace mas simple
