### ISSUE TITLE
Main o ejercicio 6??

### ISSUE THREAD

**Issue by gonzafernan** [FernandezGFG/informatica-2017#35]
Acabo de terminar el ejercicio 6, y es el ejercicio que reúne todos los anteriores. Les parece utilizarlo de main?
Pregunto antes de hacer pull request

**Comment by GinoAvanzini** [comment]
Seeh

**Comment by ichmew** [comment]
Ya lo subieron al 6??

**Comment by gonzafernan** [comment]
No, no, lo armo al main y lo subo? Confían en mi? Jajajajaja

**Comment by ichmew** [comment]
Che y después de hacer el 6 como main cómo vamos a hacer con los ejercicios siguientes?? Se van a poder acoplar a ese main??

**Comment by gonzafernan** [comment]
Claro claro, sería la primer parte del main para el ejercicio 6, la otra para matrices que ya lo arme también y al final para el Fibonacci del Gino y lo que queda. Hago un switch para que elija que sección del código usar. Les parece bien?

**Comment by GinoAvanzini** [comment]
Espectacular

**Comment by giunta** [comment]
donde esta el ejercicio 6? no lo subiste todavia o soy  muy ciego?

**Comment by giunta** [comment]
les iba a decir tambien que como el ejercicio 6 y el 13 piden que muestre todos los resultados parciales cada ejercicio deberia tener su propio printf de los resultados que hace, por ahi vi eso comentado en uno

**Comment by giunta** [comment]
lo de arriba lo solucione llamando a la funcion de visualizar la matriz despues de cada paso asi que ignorenlo jajaja
