### ISSUE TITLE
Nuevo cap Rick & Morty

### ISSUE THREAD

**Issue by gonzafernan** [FernandezGFG/informatica-2017#42]
Lo vieron? Estuvo genial jajajaja
[https://www.youtube.com/watch?v=OMmgAS5dmhA](url)

**Comment by ichmew** [comment]
Ya lo había visto, un poco turbio pero no taaan genial

**Comment by GinoAvanzini** [comment]
Naaah, estuvo re copado, tuvo un poco de todo

**Comment by giunta** [comment]
estuvo buenisimo que sea de beth y jerry
