### ISSUE TITLE
#AndresGato

### ISSUE THREAD

**Issue by gonzafernan** [FernandezGFG/informatica-2017#5]
Hay que convencer al Andrés de que también se prenda y estamos hechos

**Comment by GinoAvanzini** [comment]
Jajajaja eso es un major issue por lo que se ve

**Comment by ichmew** [comment]
Les cabe a todos manga de cracks

**Comment by GinoAvanzini** [comment]
[Andrés](https://pbs.twimg.com/media/CXWIWorWwAAez2R.png)
