### ISSUE TITLE
Sobre los comentarios y PEP8 en python

### ISSUE THREAD

**Issue by GinoAvanzini** [FernandezGFG/informatica-2017#51]
Muchachos, creo que sería una buena práctica empezar a usar más los comentarios para que le sea más fácil a los otros entender los códigos. Sobre todo para flashadas que encontramos en internet y no se entienden fácilmente.
Además creo que en python deberíamos seguir las normas de PEP8. Hace que sea más entendible y fácil de leer todo en Python. Para eso en atom hay un par de paquetes de los que pasó el wafle (creo que el linter-pycodestyle). Además hay un paquete que se llama beautify o algo así en el que vos escribis el código y después te arregla todo, pero no lo he probado.

**Comment by giunta** [comment]
jaja justo estaba viendo lo de la PEP 8.
Esta bueno hacerlo asi
