### ISSUE TITLE
Esta cosa

### ISSUE THREAD

**Issue by gonzafernan** [FernandezGFG/informatica-2017#6]
Esta porquería es para el martes que viene según lo que tengo en el mail.

**Comment by giunta** [comment]
y si, pensabas que era para mañana?

**Comment by GinoAvanzini** [comment]
Yo creí haber escuchado que la clase pasada dijo que era para mañana. Igual claramente no iba a estar terminado para mañana

**Comment by giunta** [comment]
nope claramente

**Comment by GinoAvanzini** [comment]
Seba, no te enojes

**Comment by giunta** [comment]
jajajajaja

**Comment by gonzafernan** [comment]
No te enojes Seba

**Comment by giunta** [comment]
no me enojoo

**Comment by ichmew** [comment]
Calmate Seba no te enojes
