### ISSUE TITLE
que se supone que hace esto?

### ISSUE THREAD

**Issue by giunta** [FernandezGFG/informatica-2017#9]
https://github.com/FernandezGFG/informatica-2017/blob/81aade02ba28ee7159c52044877f7b0c29baca42/workspace.c#L16

**Comment by GinoAvanzini** [comment]
Creo que es algo que había hecho el gonza, me parece que lo podemos borrar. De última hacé un pull branch borrando el archivo y aprobamos (o no) la pull request

**Comment by giunta** [comment]
o les pregunto a este par ahora
